// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: v3/int64.proto

package v3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SingleInt64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fut int64 `protobuf:"varint,1,opt,name=fut,proto3" json:"fut,omitempty"`
}

func (x *SingleInt64) Reset() {
	*x = SingleInt64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v3_int64_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleInt64) ProtoMessage() {}

func (x *SingleInt64) ProtoReflect() protoreflect.Message {
	mi := &file_v3_int64_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleInt64.ProtoReflect.Descriptor instead.
func (*SingleInt64) Descriptor() ([]byte, []int) {
	return file_v3_int64_proto_rawDescGZIP(), []int{0}
}

func (x *SingleInt64) GetFut() int64 {
	if x != nil {
		return x.Fut
	}
	return 0
}

type MultipleInt64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	One int64 `protobuf:"varint,1,opt,name=one,proto3" json:"one,omitempty"`
	Two int64 `protobuf:"varint,2,opt,name=two,proto3" json:"two,omitempty"`
}

func (x *MultipleInt64) Reset() {
	*x = MultipleInt64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v3_int64_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipleInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleInt64) ProtoMessage() {}

func (x *MultipleInt64) ProtoReflect() protoreflect.Message {
	mi := &file_v3_int64_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleInt64.ProtoReflect.Descriptor instead.
func (*MultipleInt64) Descriptor() ([]byte, []int) {
	return file_v3_int64_proto_rawDescGZIP(), []int{1}
}

func (x *MultipleInt64) GetOne() int64 {
	if x != nil {
		return x.One
	}
	return 0
}

func (x *MultipleInt64) GetTwo() int64 {
	if x != nil {
		return x.Two
	}
	return 0
}

var File_v3_int64_proto protoreflect.FileDescriptor

var file_v3_int64_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x76, 0x33, 0x2f, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x67, 0x6f, 0x2e, 0x65, 0x6e,
	0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x33, 0x22, 0x1f, 0x0a, 0x0b, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x75, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x03, 0x66, 0x75, 0x74, 0x22, 0x33, 0x0a, 0x0d, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x70, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x6e, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6f, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x77, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x74, 0x77, 0x6f, 0x42, 0x27, 0x5a,
	0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x67, 0x6f, 0x2f, 0x65, 0x6e, 0x63,
	0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x33, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v3_int64_proto_rawDescOnce sync.Once
	file_v3_int64_proto_rawDescData = file_v3_int64_proto_rawDesc
)

func file_v3_int64_proto_rawDescGZIP() []byte {
	file_v3_int64_proto_rawDescOnce.Do(func() {
		file_v3_int64_proto_rawDescData = protoimpl.X.CompressGZIP(file_v3_int64_proto_rawDescData)
	})
	return file_v3_int64_proto_rawDescData
}

var file_v3_int64_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v3_int64_proto_goTypes = []interface{}{
	(*SingleInt64)(nil),   // 0: protobuf_go.encoding.testing.proto.v3.SingleInt64
	(*MultipleInt64)(nil), // 1: protobuf_go.encoding.testing.proto.v3.MultipleInt64
}
var file_v3_int64_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v3_int64_proto_init() }
func file_v3_int64_proto_init() {
	if File_v3_int64_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v3_int64_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleInt64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v3_int64_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultipleInt64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v3_int64_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v3_int64_proto_goTypes,
		DependencyIndexes: file_v3_int64_proto_depIdxs,
		MessageInfos:      file_v3_int64_proto_msgTypes,
	}.Build()
	File_v3_int64_proto = out.File
	file_v3_int64_proto_rawDesc = nil
	file_v3_int64_proto_goTypes = nil
	file_v3_int64_proto_depIdxs = nil
}
