// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: v3/message.proto

package v3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SingleMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fut *SubMessage `protobuf:"bytes,1,opt,name=fut,proto3" json:"fut,omitempty"`
}

func (x *SingleMessage) Reset() {
	*x = SingleMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v3_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMessage) ProtoMessage() {}

func (x *SingleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v3_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMessage.ProtoReflect.Descriptor instead.
func (*SingleMessage) Descriptor() ([]byte, []int) {
	return file_v3_message_proto_rawDescGZIP(), []int{0}
}

func (x *SingleMessage) GetFut() *SubMessage {
	if x != nil {
		return x.Fut
	}
	return nil
}

type MultipleMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	One *SubMessage      `protobuf:"bytes,1,opt,name=one,proto3" json:"one,omitempty"`
	Two []*SubSubMessage `protobuf:"bytes,2,rep,name=two,proto3" json:"two,omitempty"`
}

func (x *MultipleMessage) Reset() {
	*x = MultipleMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v3_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleMessage) ProtoMessage() {}

func (x *MultipleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v3_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleMessage.ProtoReflect.Descriptor instead.
func (*MultipleMessage) Descriptor() ([]byte, []int) {
	return file_v3_message_proto_rawDescGZIP(), []int{1}
}

func (x *MultipleMessage) GetOne() *SubMessage {
	if x != nil {
		return x.One
	}
	return nil
}

func (x *MultipleMessage) GetTwo() []*SubSubMessage {
	if x != nil {
		return x.Two
	}
	return nil
}

type SubMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sone string         `protobuf:"bytes,1,opt,name=sone,proto3" json:"sone,omitempty"`
	Stwo *SubSubMessage `protobuf:"bytes,2,opt,name=stwo,proto3" json:"stwo,omitempty"`
}

func (x *SubMessage) Reset() {
	*x = SubMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v3_message_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubMessage) ProtoMessage() {}

func (x *SubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v3_message_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubMessage.ProtoReflect.Descriptor instead.
func (*SubMessage) Descriptor() ([]byte, []int) {
	return file_v3_message_proto_rawDescGZIP(), []int{2}
}

func (x *SubMessage) GetSone() string {
	if x != nil {
		return x.Sone
	}
	return ""
}

func (x *SubMessage) GetStwo() *SubSubMessage {
	if x != nil {
		return x.Stwo
	}
	return nil
}

type SubSubMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ssfut string `protobuf:"bytes,1,opt,name=ssfut,proto3" json:"ssfut,omitempty"`
}

func (x *SubSubMessage) Reset() {
	*x = SubSubMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v3_message_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubSubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubSubMessage) ProtoMessage() {}

func (x *SubSubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_v3_message_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubSubMessage.ProtoReflect.Descriptor instead.
func (*SubSubMessage) Descriptor() ([]byte, []int) {
	return file_v3_message_proto_rawDescGZIP(), []int{3}
}

func (x *SubSubMessage) GetSsfut() string {
	if x != nil {
		return x.Ssfut
	}
	return ""
}

var File_v3_message_proto protoreflect.FileDescriptor

var file_v3_message_proto_rawDesc = []byte{
	0x0a, 0x10, 0x76, 0x33, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x67, 0x6f, 0x2e,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x33, 0x22, 0x54, 0x0a, 0x0d, 0x53, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x43, 0x0a, 0x03, 0x66, 0x75,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x5f, 0x67, 0x6f, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x74,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x33, 0x2e,
	0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x66, 0x75, 0x74, 0x22,
	0x9e, 0x01, 0x0a, 0x0f, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x43, 0x0a, 0x03, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x67, 0x6f, 0x2e, 0x65,
	0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x33, 0x2e, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x03, 0x6f, 0x6e, 0x65, 0x12, 0x46, 0x0a, 0x03, 0x74, 0x77, 0x6f, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x5f, 0x67, 0x6f, 0x2e, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x74, 0x65, 0x73,
	0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x33, 0x2e, 0x53, 0x75,
	0x62, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x03, 0x74, 0x77, 0x6f,
	0x22, 0x6a, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6f,
	0x6e, 0x65, 0x12, 0x48, 0x0a, 0x04, 0x73, 0x74, 0x77, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x34, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x5f, 0x67, 0x6f, 0x2e, 0x65,
	0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x33, 0x2e, 0x53, 0x75, 0x62, 0x53, 0x75, 0x62, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x04, 0x73, 0x74, 0x77, 0x6f, 0x22, 0x25, 0x0a, 0x0d,
	0x53, 0x75, 0x62, 0x53, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x73, 0x66, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x73,
	0x66, 0x75, 0x74, 0x42, 0x27, 0x5a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d,
	0x67, 0x6f, 0x2f, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x2f, 0x74, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x33, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v3_message_proto_rawDescOnce sync.Once
	file_v3_message_proto_rawDescData = file_v3_message_proto_rawDesc
)

func file_v3_message_proto_rawDescGZIP() []byte {
	file_v3_message_proto_rawDescOnce.Do(func() {
		file_v3_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_v3_message_proto_rawDescData)
	})
	return file_v3_message_proto_rawDescData
}

var file_v3_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v3_message_proto_goTypes = []interface{}{
	(*SingleMessage)(nil),   // 0: protobuf_go.encoding.testing.proto.v3.SingleMessage
	(*MultipleMessage)(nil), // 1: protobuf_go.encoding.testing.proto.v3.MultipleMessage
	(*SubMessage)(nil),      // 2: protobuf_go.encoding.testing.proto.v3.SubMessage
	(*SubSubMessage)(nil),   // 3: protobuf_go.encoding.testing.proto.v3.SubSubMessage
}
var file_v3_message_proto_depIdxs = []int32{
	2, // 0: protobuf_go.encoding.testing.proto.v3.SingleMessage.fut:type_name -> protobuf_go.encoding.testing.proto.v3.SubMessage
	2, // 1: protobuf_go.encoding.testing.proto.v3.MultipleMessage.one:type_name -> protobuf_go.encoding.testing.proto.v3.SubMessage
	3, // 2: protobuf_go.encoding.testing.proto.v3.MultipleMessage.two:type_name -> protobuf_go.encoding.testing.proto.v3.SubSubMessage
	3, // 3: protobuf_go.encoding.testing.proto.v3.SubMessage.stwo:type_name -> protobuf_go.encoding.testing.proto.v3.SubSubMessage
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v3_message_proto_init() }
func file_v3_message_proto_init() {
	if File_v3_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v3_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v3_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultipleMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v3_message_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v3_message_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubSubMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v3_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v3_message_proto_goTypes,
		DependencyIndexes: file_v3_message_proto_depIdxs,
		MessageInfos:      file_v3_message_proto_msgTypes,
	}.Build()
	File_v3_message_proto = out.File
	file_v3_message_proto_rawDesc = nil
	file_v3_message_proto_goTypes = nil
	file_v3_message_proto_depIdxs = nil
}
