on:
    push:
        paths-ignore:
            - '**/**.md'

concurrency: ci-${{ github.ref }}

name: protobuf-go-ci

jobs:
    ci:
      name: "CI"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Install go
          uses: actions/setup-go@v3
          with:
            go-version: '^1.21.0'
        - name: "Installed go version"
          run: go version
        - name: "Build"
          run: |
            go build ./...
        - name: "Test"
          run: |
            go test ./... -race -coverpkg=all -coverprofile=coverage.out
        - name: "Exclude codecoverage and combine coverage files" # known bug that files parameter is ignored https://github.com/codecov/codecov-action/issues/1285 so unfiltered files must be overriden
          run: |
            grep -v -E -f .covignore coverage.out > coverage.filtered.out
            mv coverage.filtered.out coverage.out
        - name: "Code coverage"
          uses: codecov/codecov-action@v3
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            fail_ci_if_error: true