on:
    workflow_dispatch

env:
    MAJOR_MINOR_PATCH: 0.2.1
    FEATURE_BRANCH_BUILD: 1

concurrency: release-${{ github.ref }}

name: protobuf-go-release

jobs:
    publish:
      name: "Publish"
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@v4
        - name: Version suffix
          id: version_suffix
          run: |
            if [[ ${{ github.ref }} == "refs/heads/${{ github.event.repository.default_branch }}" ]]; then
                echo 'for default branch pipeline'
                USE=false
                SUFFIX=''
                EXTENSION=''
            else
                echo 'for feature branch pipeline'
                USE=true
                SUFFIX=${GITHUB_REF##*/}.${{env.FEATURE_BRANCH_BUILD}}
                EXTENSION="-${SUFFIX}"
            fi
            echo 'use_version_suffix' $USE
            echo 'version_suffix: ' $SUFFIX
            echo "use_version_suffix=$USE" >> $GITHUB_OUTPUT
            echo "version_suffix=$SUFFIX" >> $GITHUB_OUTPUT
            echo "extension=$EXTENSION" >> $GITHUB_OUTPUT
        - name : Semantic version
          id: semantic_version
          run: |
            SEMANTIC_VERSION="${{ env.MAJOR_MINOR_PATCH }}"
            SEMANTIC_VERSION="${SEMANTIC_VERSION}${{ steps.version_suffix.outputs.extension }}"
            echo 'MAJOR_MINOR_PATCH: ' $MAJOR_MINOR_PATCH
            echo 'SEMANTIC_VERSION: ' $SEMANTIC_VERSION
            echo "semantic_version=$SEMANTIC_VERSION" >> $GITHUB_OUTPUT
            echo "major_minor_patch=$MAJOR_MINOR_PATCH" >> $GITHUB_OUTPUT
        - name: Create semantic versioning git tag for golang
          uses: actions/github-script@v7
          with:
            script: |
              github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: "refs/tags/v${{ steps.semantic_version.outputs.semantic_version }}",
                sha: context.sha
              })
